### ISSUE TITLE
less.inc.php plugin doesn't work when placed in folder lessphp

### ISSUE THREAD

**Issue by bartvandebiezen** [janstieler/kirby-lessphp#2]
When I upload the plugin file in root of 'plugins', it works great, but not in a subfolder 'lessphp'.

**Comment by janstieler** [comment]
Hi,
mmh, what I have to say is that I don't have tested it yet with Kirby 2 but in Kirby 1 it works on my installations.
I'll do to take a look with Kirby 2.

Kind regards
